### PR TITLE
Add use-full-config flag to enable full config without creating a file

### PR DESCRIPTION
**Pull request by twardakm**
Sometimes it is usefull to use procs with full config without creating
separate config file (for example if we ask someone to collect some
data for us).

It also modifies CONFIG_ALL static to the same values as are in
config/large.toml.

### CODE REVIEW

**Comment by twardakm** [comment]
I started to use procs on embedded devices to gather some CPU / RSS data while debugging, but I struggled all the time with creating config file, just to have RSS value.

I think it would be beneficial to be able to run procs without this burden, and a flag is in my opinion a nice solution here.

**Comment by dalance** [comment]
Thank you for your request.
I think this is good idea, but there is some considerations.

* The `CONFIG_ALL` is for test of all columns. You should add another static like `CONFIG_LARGE`.
* It may be useful that some embedded configs can be selected through like `--use-config default`, `--use-config large`.

**Comment by twardakm** [comment]
Thanks for your suggestions, they make perfect sense. I will change my merge request soon.

**Comment by pleshevskiy** [comment]
> It may be useful that some embedded configs can be selected through like --use-config default, --use-config large.

I totally agree! I wanted to create an issue, that would be useful if we could use different configs for different situations.

**Comment by dalance** [comment]
I added `--use-config` and built-in configs ( `default` and `large` ) which are the same as `config/*.toml`.
So I'll close this PR.

**Pull request closed without merging**
