### PR TITLE
Feature/kthreads

### PR DESCRIPTION
**Pull request by cristiano-prato**
I often need to remove kthreads from the output of top/ps commands, to only check what is running in userspace.
For this reason I would like an option to filter out them.
I also prefer to print them out surrounded by square brackets to easily eyeball them when not filtered out.

### CODE REVIEW

**Comment by dalance** [comment]
Looks good!
I'm wondering whether `--no-kthreads` option or configuration like below.

```toml
[display]
show_kthreads = false
```

How about it?

**Comment by cristiano-prato** [comment]
I think it depends on how often you want to switch between the two options (with and without kthreads). If most of the time users are not interested in kthreads, having this in the configuration is probably the best option. 90% of the time I am not interested in kthreads for example, so this would work well for me.

**Comment by dalance** [comment]
I think so too. Could you change to configuration?

**Comment by cristiano-prato** [comment]
Sure!

**Comment by dalance** [comment]
Thanks!
I'll merge this PR.

**Pull request merged**
